spring.application.name=domitra

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/domitra?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=MySystem@23
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Hibernate is saying it doesn't need it anymore in version 6 \u2014 it detects MySQL automatically. Remove it to keep things clean.
# Also add this one line to remove the open-in-view warning:
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=****
spring.security.oauth2.client.registration.google.client-secret=****
spring.security.oauth2.client.registration.google.scope=email,profile

# Cloudinary
cloudinary.cloud-name=dzgdt7hte
cloudinary.api-key=138834293439352
cloudinary.api-secret=errbCYBjeWn5ynCnFPUjdKMFiQY

# App
server.port=8080


